### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by thehappydinoa** [mariusmotea/Google-Image-Thumbnails#1]
Hey man,
I would highly suggest using [random-agent](https://pypi.python.org/pypi/fake-useragent)

**Comment by mariusmotea** [comment]
Hi,
I will use it in case google will made some changes to api. Now using that simple agent header is doing the trick. I don't expect this to work forever...but currently is working fine.

**Comment by thehappydinoa** [comment]
Ah ok
